language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- ruby-head
bundler_args: "--jobs=4"
cache: bundler
before_install:
- gem update --system --no-document
- gem install bundler --no-document
before_script:
- export CODECLIMATE_REPO_TOKEN=82d5b98775f7517294816845556790951867aba59db59a59178f0bed50a44216
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter || true
branches:
  only:
  - master
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
notifications:
  slack:
    secure: GZZkyEmKBlwECsm47m+8XOcQhNcXciPsUhXfrAFBfTRxwCCy7myUBXL7aSV9T10N+QQX1rVilkD1zHRgX3U2S/S8xQfafrYiv5ZNDXp6xrNqGPC3WNGGY9PzvhJxpacp05qXxWXR5ml3Uk+1IZIoWJIPNtUVAgVO2gg6eLegHMiR2DwFmylW3nbfY6ozb6lo00rBih/k8KFqKZwo7odbdWN5LMPPH5vzO2f3sTF/3F8KsgxhESoA9hBLymDlcofEJ0gThXIH0T1WQGRmPpjJu5CSt5DAgDJxoJ/DjHy02ZJi/2vy8WnM2TGNI0sGInp/0GYb8AntpnyDw57UF2MCW4pYBqVgGfUxRHunzhLTtUI870BrQN0UHzHvnMgyxXCLZYN7rMqBuptQXRseWXzWovDHBEeGtYaEf41aOCX9bi/KC+k4FEeK6eJIXW5FXBC6TOnQTYvCx1V2BDdqH2jzxfSEtyA7rJlzDr+CajfsT25H+izqUQF7s5JxtcPuYoHXfxN420Qpfylvmje312WnccKXQKqdX4K/MWy+PM2VsU74EWCUy52flMonqKblyPWGn+Eo4LxGGRkq68lzVH02fwlF9QiIX0jjFkLPyHrw2+kxDK4g2S5+VxIOsKq2IYssXuEfGlXHuv3TRLb3Z8taqgS1zqZ5U1pVfQhLkCDSikM=
