language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
bundler_args: "--jobs=4"
cache: bundler
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RUBYOPT=$RSPEC_RUBYOPT bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RSPEC_RUBYOPT="--jit"
    - rvm: ruby-head
      env: RSPEC_RUBYOPT="--jit"
sudo: false
notifications:
  slack:
    secure: GZZkyEmKBlwECsm47m+8XOcQhNcXciPsUhXfrAFBfTRxwCCy7myUBXL7aSV9T10N+QQX1rVilkD1zHRgX3U2S/S8xQfafrYiv5ZNDXp6xrNqGPC3WNGGY9PzvhJxpacp05qXxWXR5ml3Uk+1IZIoWJIPNtUVAgVO2gg6eLegHMiR2DwFmylW3nbfY6ozb6lo00rBih/k8KFqKZwo7odbdWN5LMPPH5vzO2f3sTF/3F8KsgxhESoA9hBLymDlcofEJ0gThXIH0T1WQGRmPpjJu5CSt5DAgDJxoJ/DjHy02ZJi/2vy8WnM2TGNI0sGInp/0GYb8AntpnyDw57UF2MCW4pYBqVgGfUxRHunzhLTtUI870BrQN0UHzHvnMgyxXCLZYN7rMqBuptQXRseWXzWovDHBEeGtYaEf41aOCX9bi/KC+k4FEeK6eJIXW5FXBC6TOnQTYvCx1V2BDdqH2jzxfSEtyA7rJlzDr+CajfsT25H+izqUQF7s5JxtcPuYoHXfxN420Qpfylvmje312WnccKXQKqdX4K/MWy+PM2VsU74EWCUy52flMonqKblyPWGn+Eo4LxGGRkq68lzVH02fwlF9QiIX0jjFkLPyHrw2+kxDK4g2S5+VxIOsKq2IYssXuEfGlXHuv3TRLb3Z8taqgS1zqZ5U1pVfQhLkCDSikM=
env:
  global:
    - CC_TEST_REPORTER_ID=82d5b98775f7517294816845556790951867aba59db59a59178f0bed50a44216
